### ISSUE TITLE
Nixos module as a Flake

### ISSUE THREAD

**Issue by kamadorueda** [flox/nixos-module#1]
I'm trying to install Flox on my system, however the installation instructions:
- Are not pinned (so they self-update to master) which goes against the reproducibility benefits of Nix
- Are for Nix stable (I use Nix Flakes)
- Have different syntax in order to work under a NixOS with Flakes
- Are --impure (master does not have a commit nor a hash)

It's a simple addition though:
- https://github.com/kamadorueda/machine/commit/34d6438621f43c3ee3c62d591585ae7fd0cfb4d2#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0

**Comment by limeytexan** [comment]
No longer using the old nixos-module.
