### ISSUE TITLE
Having to rebuild twice

### ISSUE THREAD

**Issue by kamadorueda** [flox/nixos-module#2]
Ideally a NixOS system should go from scratch to a fully working system in a single activation (nixos-rebuild switch)

However, having to flip `services.flox.substituterAdded` requires two serial activations. This is some form of "state", and removing it would make installing Flox simpler, as well as following the immutability philosophy of Nix

Some details I have not checked:
- What happens if I deploy a `substitutedAdded = true;` into a blank machine? would it fail?

**Comment by limeytexan** [comment]
Closing out issues pertaining to old beta
